[build]
  publish="dist/atm-app-frontend"
  command="npm run build:in-memory "
  functions = "functions"
#[[redirects]]
#  from = "pro/*"
#  to = "/.netlify/functions/netlifyproxyawsapigateway/*"
#  status = 200
#  force = true
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://676f9d600a5c634129a8769b--mellifluous-queijadas-f17050.netlify.app" 
    Access-Control-Allow-Methods = "DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT"
    Access-Control-Allow-Credentials = "true"
[[headers]]
  for = "/.netlify/functions/netlifyproxyawsapigateway/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://676f9d600a5c634129a8769b--mellifluous-queijadas-f17050.netlify.app" 
    Access-Control-Allow-Methods = "DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT"
    Access-Control-Allow-Credentials = "true"
[functions]
  # Directory with serverless functions, including background
  # functions, to deploy. This is an absolute path relative to the 
  # base directory, which is the root by default (/).
  directory = "netlify/functions/"


# Use [dev] to set configuration overrides for local
# development environments run using Netlify Dev - except
# targetPort 8888 did not work 
# for environment variables. Environment variables for Netlify
# Dev should be set under [context.dev.environment] instead.
[dev]
  command = "npm start"
  publish = "dist/netlify"